// /lib/constants.ts

export const NSE_SYMBOLS = [
  'RELIANCE.NS','TCS.NS','HDFCBANK.NS','INFY.NS','ICICIBANK.NS',
  'HINDUNILVR.NS','SBIN.NS','BHARTIARTL.NS','ITC.NS','KOTAKBANK.NS',
  'LT.NS','AXISBANK.NS','ASIANPAINT.NS','MARUTI.NS','SUNPHARMA.NS',
  'TITAN.NS','BAJFINANCE.NS','WIPRO.NS','ULTRACEMCO.NS','ONGC.NS',
  'POWERGRID.NS','NTPC.NS','TECHM.NS','NESTLEIND.NS','HCLTECH.NS',
  'BAJAJFINSV.NS','TATAMOTORS.NS','DIVISLAB.NS','JSWSTEEL.NS',
  'TATACONSUM.NS','HINDALCO.NS','ADANIENT.NS','COALINDIA.NS',
  'DRREDDY.NS','CIPLA.NS','BPCL.NS','EICHERMOT.NS','GRASIM.NS',
  'HEROMOTOCO.NS','INDUSINDBK.NS','BRITANNIA.NS','APOLLOHOSP.NS',
  'BAJAJ-AUTO.NS','M&M.NS','SBILIFE.NS','HDFCLIFE.NS',
  'UPL.NS','VEDL.NS','TATASTEEL.NS','ADANIPORTS.NS'
]

export const INDEX_SYMBOLS = ['^NSEI','^BSESN','^NSEBANK','^CNXIT']

export const GLOBAL_SYMBOLS = [
  '^GSPC','^IXIC','^DJI','^FTSE','^N225','^HSI',
  'CL=F','GC=F','INR=X'
]

export const SECTOR_MAP: Record<string, string[]> = {
  'IT': ['TCS.NS','INFY.NS','WIPRO.NS','HCLTECH.NS','TECHM.NS'],
  'Banking': ['HDFCBANK.NS','ICICIBANK.NS','SBIN.NS','KOTAKBANK.NS',
              'AXISBANK.NS','INDUSINDBK.NS'],
  'FMCG': ['HINDUNILVR.NS','ITC.NS','NESTLEIND.NS','BRITANNIA.NS',
           'TATACONSUM.NS'],
  'Auto': ['MARUTI.NS','TATAMOTORS.NS','EICHERMOT.NS','HEROMOTOCO.NS',
           'BAJAJ-AUTO.NS','M&M.NS'],
  'Pharma': ['SUNPHARMA.NS','DRREDDY.NS','CIPLA.NS','DIVISLAB.NS',
             'APOLLOHOSP.NS'],
  'Energy': ['RELIANCE.NS','ONGC.NS','BPCL.NS','POWERGRID.NS',
             'NTPC.NS','COALINDIA.NS'],
  'Metal': ['TATASTEEL.NS','JSWSTEEL.NS','HINDALCO.NS','VEDL.NS'],
  'Finance': ['BAJFINANCE.NS','BAJAJFINSV.NS','SBILIFE.NS','HDFCLIFE.NS'],
  'Infra': ['LT.NS','ADANIPORTS.NS','ADANIENT.NS','ULTRACEMCO.NS','GRASIM.NS'],
  'Telecom': ['BHARTIARTL.NS'],
  'Consumer': ['ASIANPAINT.NS','TITAN.NS','UPL.NS'],
}

export const INDEX_NAMES: Record<string, string> = {
  '^NSEI': 'NIFTY 50',
  '^BSESN': 'SENSEX',
  '^NSEBANK': 'BANK NIFTY',
  '^CNXIT': 'NIFTY IT',
}

export const MARKET_HOURS = {
  open: { hour: 9, minute: 15 },
  close: { hour: 15, minute: 30 },
  timezone: 'Asia/Kolkata',
}
